// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odlorlbwjbxuidxaafui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kbG9ybGJ3amJ4dWlkeGFhZnVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNDg5MDgsImV4cCI6MjA2MjkyNDkwOH0.Mc41JjKa94_SIZNyhsGX-Dg4WjBqLr24V7BPD4ZfNlo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);